# Generated by Django 3.2.13 on 2022-06-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('marque', models.CharField(choices=[('GARMIN', 'GARMIN'), ('AUTRE', 'AUTRE')], default='GARMIN', max_length=225)),
                ('model', models.CharField(blank=True, max_length=225, null=True)),
                ('prix_achat', models.PositiveIntegerField(default=0)),
                ('date_achat', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'gps',
                'verbose_name_plural': 'GPS',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Imprimante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('numero_serie', models.CharField(max_length=225)),
                ('marque', models.CharField(choices=[('ASUS', 'ASUS'), ('DELL', 'DELL'), ('HP', 'HP')], max_length=225)),
                ('model', models.CharField(blank=True, max_length=225, null=True)),
                ('utilisateur', models.CharField(max_length=225)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('prix_achat', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'imprimantes',
                'verbose_name_plural': 'IMPRIMANTES',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('numero_serie', models.CharField(max_length=225)),
                ('marque', models.CharField(choices=[('ASUS', 'ASUS'), ('DELL', 'DELL'), ('HP', 'HP')], max_length=225)),
                ('model', models.CharField(blank=True, max_length=225, null=True)),
                ('utilisateur', models.CharField(max_length=225)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('prix_achat', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ordinateurs',
                'verbose_name_plural': 'ORDNATEURS',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Sortiequipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('accessoires', models.ManyToManyField(to='equipements.Accessoire')),
                ('gps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.gps')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.projet')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.technicien')),
            ],
            options={
                'verbose_name': 'sortie equipement',
                'verbose_name_plural': 'SORTIE EQUIPEMENTS',
                'ordering': ['-date_sortie'],
            },
        ),
    ]
